function plotObjects(x_all, y_all, clusters, objects, dangerousObject_side, dangerousObject_back)

numScans = size(x_all,1);

colors = lines(50);

% remove color red from all possible colors for normal clusters 
colors(all(colors(:,1) > 0.8 & colors(:,2) < 0.3,2),:) = [];

for n = 1:numScans

    x_scan = x_all(n,:);
    y_scan = y_all(n,:);

    clf;

    scatter(x_scan, y_scan, 8, 'b', 'filled');
    hold on;

    grid on;
    grid minor;

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % plot normal clusters
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    for k = 1:length(clusters)

        if clusters{k}.numScan == n

            clusterId = clusters{k}.id;

            colorIndex = mod(clusterId - 1, size(colors,1)) + 1;

            scatter( ...
                clusters{k}.x, ...
                clusters{k}.y, ...
                20, ...
                colors(colorIndex,:), ...
                'filled');

            centerX = clusters{k}.meanValue.centerX;
            centerY = clusters{k}.meanValue.centerY;

            objectIndex = find([objects.id] == clusterId,1);

            if ~isempty(objectIndex)

                if objects(objectIndex).approaching

                    quiver( ...
                        centerX, ...
                        centerY, ...
                        0, ...
                        -0.3, ...
                        0, ...
                        'Color','r', ...
                        'LineWidth',2, ...
                        'MaxHeadSize',4);

                else

                    quiver( ...
                        centerX, ...
                        centerY, ...
                        0, ...
                        0.3, ...
                        0, ...
                        'Color','g', ...
                        'LineWidth',2, ...
                        'MaxHeadSize',4);

                end
            end

            text( ...
                centerX + 0.1, ...
                centerY, ...
                sprintf('ID %d', clusterId), ...
                'Color','w', ...
                'FontSize',8);

        end
    end

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % paint danger in red
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    for d = 1:length(dangerousObject_side)

        if dangerousObject_side{d}.scannumber == n

            scatter( ...
                dangerousObject_side{d}.x, ...
                dangerousObject_side{d}.y, ...
                50, ...
                'r', ...
                'filled');

            text( ...
                mean(dangerousObject_side{d}.x), ...
                mean(dangerousObject_side{d}.y), ...
                sprintf('GEFAHR ID %d', ...
                dangerousObject_side{d}.clusterId), ...
                'Color','r', ...
                'FontWeight','bold', ...
                'FontSize',10);

        end

    end

    for d = 1:length(dangerousObject_back)

        if dangerousObject_back{d}.scannumber == n

            scatter( ...
                dangerousObject_back{d}.x, ...
                dangerousObject_back{d}.y, ...
                50, ...
                'r', ...
                'filled');

            text( ...
                mean(dangerousObject_back{d}.x), ...
                mean(dangerousObject_back{d}.y), ...
                sprintf('GEFAHR ID %d', ...
                dangerousObject_back{d}.clusterId), ...
                'Color','r', ...
                'FontWeight','bold', ...
                'FontSize',10);

        end

    end

    axis equal;

    title(['Scan ' num2str(n)]);

    xlim([-8 8]);
    ylim([-8 8]);

    drawnow;

    pause(0.01);

end

end